/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LaundrySolutionRouteImport } from './routes/laundry-solution'
import { Route as LaundryBasketAnalysisResultRouteImport } from './routes/laundry-basket-analysis-result'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalysisFailedRouteImport } from './routes/analysis-failed'
import { Route as AnalysingRouteImport } from './routes/analysing'
import { Route as AnalysisRouteRouteImport } from './routes/analysis/route'
import { Route as WithNavLayoutRouteRouteImport } from './routes/_with-nav-layout/route'
import { Route as WithNavLayoutIndexRouteImport } from './routes/_with-nav-layout/index'
import { Route as WithNavLayoutWikiRouteImport } from './routes/_with-nav-layout/wiki'
import { Route as WithNavLayoutLabelAnalysisRouteImport } from './routes/_with-nav-layout/label-analysis'
import { Route as WithNavLayoutLaundryBasketRouteRouteImport } from './routes/_with-nav-layout/laundry-basket.route'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundrySolutionRoute = LaundrySolutionRouteImport.update({
  id: '/laundry-solution',
  path: '/laundry-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryBasketAnalysisResultRoute =
  LaundryBasketAnalysisResultRouteImport.update({
    id: '/laundry-basket-analysis-result',
    path: '/laundry-basket-analysis-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisFailedRoute = AnalysisFailedRouteImport.update({
  id: '/analysis-failed',
  path: '/analysis-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysingRoute = AnalysingRouteImport.update({
  id: '/analysing',
  path: '/analysing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRouteRoute = AnalysisRouteRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavLayoutRouteRoute = WithNavLayoutRouteRouteImport.update({
  id: '/_with-nav-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavLayoutIndexRoute = WithNavLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithNavLayoutRouteRoute,
} as any)
const WithNavLayoutWikiRoute = WithNavLayoutWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => WithNavLayoutRouteRoute,
} as any)
const WithNavLayoutLabelAnalysisRoute =
  WithNavLayoutLabelAnalysisRouteImport.update({
    id: '/label-analysis',
    path: '/label-analysis',
    getParentRoute: () => WithNavLayoutRouteRoute,
  } as any)
const WithNavLayoutLaundryBasketRouteRoute =
  WithNavLayoutLaundryBasketRouteRouteImport.update({
    id: '/laundry-basket',
    path: '/laundry-basket',
    getParentRoute: () => WithNavLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/analysis': typeof AnalysisRouteRoute
  '/analysing': typeof AnalysingRoute
  '/analysis-failed': typeof AnalysisFailedRoute
  '/chat': typeof ChatRoute
  '/laundry-basket-analysis-result': typeof LaundryBasketAnalysisResultRoute
  '/laundry-solution': typeof LaundrySolutionRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/laundry-basket': typeof WithNavLayoutLaundryBasketRouteRoute
  '/label-analysis': typeof WithNavLayoutLabelAnalysisRoute
  '/wiki': typeof WithNavLayoutWikiRoute
  '/': typeof WithNavLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/analysis': typeof AnalysisRouteRoute
  '/analysing': typeof AnalysingRoute
  '/analysis-failed': typeof AnalysisFailedRoute
  '/chat': typeof ChatRoute
  '/laundry-basket-analysis-result': typeof LaundryBasketAnalysisResultRoute
  '/laundry-solution': typeof LaundrySolutionRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/laundry-basket': typeof WithNavLayoutLaundryBasketRouteRoute
  '/label-analysis': typeof WithNavLayoutLabelAnalysisRoute
  '/wiki': typeof WithNavLayoutWikiRoute
  '/': typeof WithNavLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_with-nav-layout': typeof WithNavLayoutRouteRouteWithChildren
  '/analysis': typeof AnalysisRouteRoute
  '/analysing': typeof AnalysingRoute
  '/analysis-failed': typeof AnalysisFailedRoute
  '/chat': typeof ChatRoute
  '/laundry-basket-analysis-result': typeof LaundryBasketAnalysisResultRoute
  '/laundry-solution': typeof LaundrySolutionRoute
  '/onboarding': typeof OnboardingRoute
  '/splash': typeof SplashRoute
  '/_with-nav-layout/laundry-basket': typeof WithNavLayoutLaundryBasketRouteRoute
  '/_with-nav-layout/label-analysis': typeof WithNavLayoutLabelAnalysisRoute
  '/_with-nav-layout/wiki': typeof WithNavLayoutWikiRoute
  '/_with-nav-layout/': typeof WithNavLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analysis'
    | '/analysing'
    | '/analysis-failed'
    | '/chat'
    | '/laundry-basket-analysis-result'
    | '/laundry-solution'
    | '/onboarding'
    | '/splash'
    | '/laundry-basket'
    | '/label-analysis'
    | '/wiki'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analysis'
    | '/analysing'
    | '/analysis-failed'
    | '/chat'
    | '/laundry-basket-analysis-result'
    | '/laundry-solution'
    | '/onboarding'
    | '/splash'
    | '/laundry-basket'
    | '/label-analysis'
    | '/wiki'
    | '/'
  id:
    | '__root__'
    | '/_with-nav-layout'
    | '/analysis'
    | '/analysing'
    | '/analysis-failed'
    | '/chat'
    | '/laundry-basket-analysis-result'
    | '/laundry-solution'
    | '/onboarding'
    | '/splash'
    | '/_with-nav-layout/laundry-basket'
    | '/_with-nav-layout/label-analysis'
    | '/_with-nav-layout/wiki'
    | '/_with-nav-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithNavLayoutRouteRoute: typeof WithNavLayoutRouteRouteWithChildren
  AnalysisRouteRoute: typeof AnalysisRouteRoute
  AnalysingRoute: typeof AnalysingRoute
  AnalysisFailedRoute: typeof AnalysisFailedRoute
  ChatRoute: typeof ChatRoute
  LaundryBasketAnalysisResultRoute: typeof LaundryBasketAnalysisResultRoute
  LaundrySolutionRoute: typeof LaundrySolutionRoute
  OnboardingRoute: typeof OnboardingRoute
  SplashRoute: typeof SplashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry-solution': {
      id: '/laundry-solution'
      path: '/laundry-solution'
      fullPath: '/laundry-solution'
      preLoaderRoute: typeof LaundrySolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry-basket-analysis-result': {
      id: '/laundry-basket-analysis-result'
      path: '/laundry-basket-analysis-result'
      fullPath: '/laundry-basket-analysis-result'
      preLoaderRoute: typeof LaundryBasketAnalysisResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis-failed': {
      id: '/analysis-failed'
      path: '/analysis-failed'
      fullPath: '/analysis-failed'
      preLoaderRoute: typeof AnalysisFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysing': {
      id: '/analysing'
      path: '/analysing'
      fullPath: '/analysing'
      preLoaderRoute: typeof AnalysingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-nav-layout': {
      id: '/_with-nav-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithNavLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-nav-layout/': {
      id: '/_with-nav-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithNavLayoutIndexRouteImport
      parentRoute: typeof WithNavLayoutRouteRoute
    }
    '/_with-nav-layout/wiki': {
      id: '/_with-nav-layout/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WithNavLayoutWikiRouteImport
      parentRoute: typeof WithNavLayoutRouteRoute
    }
    '/_with-nav-layout/label-analysis': {
      id: '/_with-nav-layout/label-analysis'
      path: '/label-analysis'
      fullPath: '/label-analysis'
      preLoaderRoute: typeof WithNavLayoutLabelAnalysisRouteImport
      parentRoute: typeof WithNavLayoutRouteRoute
    }
    '/_with-nav-layout/laundry-basket': {
      id: '/_with-nav-layout/laundry-basket'
      path: '/laundry-basket'
      fullPath: '/laundry-basket'
      preLoaderRoute: typeof WithNavLayoutLaundryBasketRouteRouteImport
      parentRoute: typeof WithNavLayoutRouteRoute
    }
  }
}

interface WithNavLayoutRouteRouteChildren {
  WithNavLayoutLaundryBasketRouteRoute: typeof WithNavLayoutLaundryBasketRouteRoute
  WithNavLayoutLabelAnalysisRoute: typeof WithNavLayoutLabelAnalysisRoute
  WithNavLayoutWikiRoute: typeof WithNavLayoutWikiRoute
  WithNavLayoutIndexRoute: typeof WithNavLayoutIndexRoute
}

const WithNavLayoutRouteRouteChildren: WithNavLayoutRouteRouteChildren = {
  WithNavLayoutLaundryBasketRouteRoute: WithNavLayoutLaundryBasketRouteRoute,
  WithNavLayoutLabelAnalysisRoute: WithNavLayoutLabelAnalysisRoute,
  WithNavLayoutWikiRoute: WithNavLayoutWikiRoute,
  WithNavLayoutIndexRoute: WithNavLayoutIndexRoute,
}

const WithNavLayoutRouteRouteWithChildren =
  WithNavLayoutRouteRoute._addFileChildren(WithNavLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WithNavLayoutRouteRoute: WithNavLayoutRouteRouteWithChildren,
  AnalysisRouteRoute: AnalysisRouteRoute,
  AnalysingRoute: AnalysingRoute,
  AnalysisFailedRoute: AnalysisFailedRoute,
  ChatRoute: ChatRoute,
  LaundryBasketAnalysisResultRoute: LaundryBasketAnalysisResultRoute,
  LaundrySolutionRoute: LaundrySolutionRoute,
  OnboardingRoute: OnboardingRoute,
  SplashRoute: SplashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
