/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LaundrySolutionRouteImport } from './routes/laundry-solution'
import { Route as LaundryBasketAnalysisResultRouteImport } from './routes/laundry-basket-analysis-result'
import { Route as AnalysisFailedRouteImport } from './routes/analysis-failed'
import { Route as AnalysingRouteImport } from './routes/analysing'
import { Route as WithNavLayoutRouteRouteImport } from './routes/_with-nav-layout/route'
import { Route as WithNavLayoutIndexRouteImport } from './routes/_with-nav-layout/index'
import { Route as LaundryEditRouteImport } from './routes/laundry.edit'
import { Route as LabelAnaysisImageRouteImport } from './routes/label-anaysis.image'
import { Route as WithNavLayoutWikiRouteImport } from './routes/_with-nav-layout/wiki'
import { Route as WithNavLayoutLabelAnalysisRouteImport } from './routes/_with-nav-layout/label-analysis'
import { Route as WithNavLayoutLaundryBasketRouteRouteImport } from './routes/_with-nav-layout/laundry-basket.route'

const LaundrySolutionRoute = LaundrySolutionRouteImport.update({
  id: '/laundry-solution',
  path: '/laundry-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const LaundryBasketAnalysisResultRoute =
  LaundryBasketAnalysisResultRouteImport.update({
    id: '/laundry-basket-analysis-result',
    path: '/laundry-basket-analysis-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnalysisFailedRoute = AnalysisFailedRouteImport.update({
  id: '/analysis-failed',
  path: '/analysis-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysingRoute = AnalysingRouteImport.update({
  id: '/analysing',
  path: '/analysing',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavLayoutRouteRoute = WithNavLayoutRouteRouteImport.update({
  id: '/_with-nav-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavLayoutIndexRoute = WithNavLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithNavLayoutRouteRoute,
} as any)
const LaundryEditRoute = LaundryEditRouteImport.update({
  id: '/laundry/edit',
  path: '/laundry/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelAnaysisImageRoute = LabelAnaysisImageRouteImport.update({
  id: '/label-anaysis/image',
  path: '/label-anaysis/image',
  getParentRoute: () => rootRouteImport,
} as any)
const WithNavLayoutWikiRoute = WithNavLayoutWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => WithNavLayoutRouteRoute,
} as any)
const WithNavLayoutLabelAnalysisRoute =
  WithNavLayoutLabelAnalysisRouteImport.update({
    id: '/label-analysis',
    path: '/label-analysis',
    getParentRoute: () => WithNavLayoutRouteRoute,
  } as any)
const WithNavLayoutLaundryBasketRouteRoute =
  WithNavLayoutLaundryBasketRouteRouteImport.update({
    id: '/laundry-basket',
    path: '/laundry-basket',
    getParentRoute: () => WithNavLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/analysing': typeof AnalysingRoute
  '/analysis-failed': typeof AnalysisFailedRoute
  '/laundry-basket-analysis-result': typeof LaundryBasketAnalysisResultRoute
  '/laundry-solution': typeof LaundrySolutionRoute
  '/laundry-basket': typeof WithNavLayoutLaundryBasketRouteRoute
  '/label-analysis': typeof WithNavLayoutLabelAnalysisRoute
  '/wiki': typeof WithNavLayoutWikiRoute
  '/label-anaysis/image': typeof LabelAnaysisImageRoute
  '/laundry/edit': typeof LaundryEditRoute
  '/': typeof WithNavLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/analysing': typeof AnalysingRoute
  '/analysis-failed': typeof AnalysisFailedRoute
  '/laundry-basket-analysis-result': typeof LaundryBasketAnalysisResultRoute
  '/laundry-solution': typeof LaundrySolutionRoute
  '/laundry-basket': typeof WithNavLayoutLaundryBasketRouteRoute
  '/label-analysis': typeof WithNavLayoutLabelAnalysisRoute
  '/wiki': typeof WithNavLayoutWikiRoute
  '/label-anaysis/image': typeof LabelAnaysisImageRoute
  '/laundry/edit': typeof LaundryEditRoute
  '/': typeof WithNavLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_with-nav-layout': typeof WithNavLayoutRouteRouteWithChildren
  '/analysing': typeof AnalysingRoute
  '/analysis-failed': typeof AnalysisFailedRoute
  '/laundry-basket-analysis-result': typeof LaundryBasketAnalysisResultRoute
  '/laundry-solution': typeof LaundrySolutionRoute
  '/_with-nav-layout/laundry-basket': typeof WithNavLayoutLaundryBasketRouteRoute
  '/_with-nav-layout/label-analysis': typeof WithNavLayoutLabelAnalysisRoute
  '/_with-nav-layout/wiki': typeof WithNavLayoutWikiRoute
  '/label-anaysis/image': typeof LabelAnaysisImageRoute
  '/laundry/edit': typeof LaundryEditRoute
  '/_with-nav-layout/': typeof WithNavLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analysing'
    | '/analysis-failed'
    | '/laundry-basket-analysis-result'
    | '/laundry-solution'
    | '/laundry-basket'
    | '/label-analysis'
    | '/wiki'
    | '/label-anaysis/image'
    | '/laundry/edit'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analysing'
    | '/analysis-failed'
    | '/laundry-basket-analysis-result'
    | '/laundry-solution'
    | '/laundry-basket'
    | '/label-analysis'
    | '/wiki'
    | '/label-anaysis/image'
    | '/laundry/edit'
    | '/'
  id:
    | '__root__'
    | '/_with-nav-layout'
    | '/analysing'
    | '/analysis-failed'
    | '/laundry-basket-analysis-result'
    | '/laundry-solution'
    | '/_with-nav-layout/laundry-basket'
    | '/_with-nav-layout/label-analysis'
    | '/_with-nav-layout/wiki'
    | '/label-anaysis/image'
    | '/laundry/edit'
    | '/_with-nav-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WithNavLayoutRouteRoute: typeof WithNavLayoutRouteRouteWithChildren
  AnalysingRoute: typeof AnalysingRoute
  AnalysisFailedRoute: typeof AnalysisFailedRoute
  LaundryBasketAnalysisResultRoute: typeof LaundryBasketAnalysisResultRoute
  LaundrySolutionRoute: typeof LaundrySolutionRoute
  LabelAnaysisImageRoute: typeof LabelAnaysisImageRoute
  LaundryEditRoute: typeof LaundryEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/laundry-solution': {
      id: '/laundry-solution'
      path: '/laundry-solution'
      fullPath: '/laundry-solution'
      preLoaderRoute: typeof LaundrySolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laundry-basket-analysis-result': {
      id: '/laundry-basket-analysis-result'
      path: '/laundry-basket-analysis-result'
      fullPath: '/laundry-basket-analysis-result'
      preLoaderRoute: typeof LaundryBasketAnalysisResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis-failed': {
      id: '/analysis-failed'
      path: '/analysis-failed'
      fullPath: '/analysis-failed'
      preLoaderRoute: typeof AnalysisFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysing': {
      id: '/analysing'
      path: '/analysing'
      fullPath: '/analysing'
      preLoaderRoute: typeof AnalysingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-nav-layout': {
      id: '/_with-nav-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithNavLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-nav-layout/': {
      id: '/_with-nav-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithNavLayoutIndexRouteImport
      parentRoute: typeof WithNavLayoutRouteRoute
    }
    '/laundry/edit': {
      id: '/laundry/edit'
      path: '/laundry/edit'
      fullPath: '/laundry/edit'
      preLoaderRoute: typeof LaundryEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label-anaysis/image': {
      id: '/label-anaysis/image'
      path: '/label-anaysis/image'
      fullPath: '/label-anaysis/image'
      preLoaderRoute: typeof LabelAnaysisImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_with-nav-layout/wiki': {
      id: '/_with-nav-layout/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WithNavLayoutWikiRouteImport
      parentRoute: typeof WithNavLayoutRouteRoute
    }
    '/_with-nav-layout/label-analysis': {
      id: '/_with-nav-layout/label-analysis'
      path: '/label-analysis'
      fullPath: '/label-analysis'
      preLoaderRoute: typeof WithNavLayoutLabelAnalysisRouteImport
      parentRoute: typeof WithNavLayoutRouteRoute
    }
    '/_with-nav-layout/laundry-basket': {
      id: '/_with-nav-layout/laundry-basket'
      path: '/laundry-basket'
      fullPath: '/laundry-basket'
      preLoaderRoute: typeof WithNavLayoutLaundryBasketRouteRouteImport
      parentRoute: typeof WithNavLayoutRouteRoute
    }
  }
}

interface WithNavLayoutRouteRouteChildren {
  WithNavLayoutLaundryBasketRouteRoute: typeof WithNavLayoutLaundryBasketRouteRoute
  WithNavLayoutLabelAnalysisRoute: typeof WithNavLayoutLabelAnalysisRoute
  WithNavLayoutWikiRoute: typeof WithNavLayoutWikiRoute
  WithNavLayoutIndexRoute: typeof WithNavLayoutIndexRoute
}

const WithNavLayoutRouteRouteChildren: WithNavLayoutRouteRouteChildren = {
  WithNavLayoutLaundryBasketRouteRoute: WithNavLayoutLaundryBasketRouteRoute,
  WithNavLayoutLabelAnalysisRoute: WithNavLayoutLabelAnalysisRoute,
  WithNavLayoutWikiRoute: WithNavLayoutWikiRoute,
  WithNavLayoutIndexRoute: WithNavLayoutIndexRoute,
}

const WithNavLayoutRouteRouteWithChildren =
  WithNavLayoutRouteRoute._addFileChildren(WithNavLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WithNavLayoutRouteRoute: WithNavLayoutRouteRouteWithChildren,
  AnalysingRoute: AnalysingRoute,
  AnalysisFailedRoute: AnalysisFailedRoute,
  LaundryBasketAnalysisResultRoute: LaundryBasketAnalysisResultRoute,
  LaundrySolutionRoute: LaundrySolutionRoute,
  LabelAnaysisImageRoute: LabelAnaysisImageRoute,
  LaundryEditRoute: LaundryEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
